# increase the default metric limits to more realistic levels
Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 200

Metrics/AbcSize:
  Max: 100

Metrics/ClassLength:
  Max: 500

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20


# Don't be picky about string quoting
Style/PercentLiteralDelimiters:
  Enabled: false

Style/StringLiterals:
  Enabled: false

